name = "cf-workers-usagepanel"
main = "_worker.js"
compatibility_date = "2026-01-10"
keep_vars = true

[[kv_namespaces]]
binding = "KV"
id = "f969f843264a4fccb257836b3494a0b0"

routes = [
  { pattern = "cf-workers-usagepanel.209.dpdns.org", custom_domain = true }
]
